name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test-backend:
    runs-on: ubuntu-latest
    env:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      DATABASE_URL: postgresql+psycopg://postgres:password@localhost:5432/postgres

      JWT_KEY: VERY_LONG_LONG_KEY_FOR_SECURITY
      TOKEN_LIFETIME_SECONDS: 86400

      BROWSER_KEY: BROWSER_KEY
      SERVER_KEY: SERVER_KEY
    steps:
      - uses: actions/checkout@v6
      - name: Run Docker Containers
        run: docker compose up -d
      - uses: actions/setup-python@v7
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install -r backend/requirements.dev.txt
      - name: Run Tests
        run: |
          cd backend
          python -m pytest
      - name: Check containers logs
        if: failure()
        run: docker compose logs backend database
